import { StyleSheet } from "react-native";
import { myColors } from "./colors";

export const styleComp = StyleSheet.create({
    productContainer: {
        width: "98%",
        padding: 10,
        margin: 0,
        marginBottom: 25,
        borderRadius: 15,
        /*borderTopLeftRadius: 15,
        borderTopRightRadius: 5,
        borderBottomLeftRadius: 5,
        borderBottomRightRadius: 15,*/
        borderWidth: 1,
        borderColor: myColors.skyblue,
        backgroundColor: myColors.white,
        elevation: 8,
    },
    texttitle: {
        backgroundColor: myColors.navyblue,
        color: myColors.white,
        borderRadius: 10,
        padding: 10,
        fontSize: 18,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    textsubtitle: {
        textAlign: 'center',
        padding: 5,
        fontSize: 18,
        fontWeight: 'bold',
        color: myColors.mustard,
    },
    textContent:{
        fontSize: 16,
        color: myColors.navyblue,
    },
    descrip: {
        fontSize: 16,
        color: myColors.navyblue,
    },
    information: {
        color: myColors.navyblue,
        fontSize: 16,
    },
    btnsContiner:{
        width: '90%',
        backgroundColor: 'transparent',
        flexDirection: "row",
    },
    btnContiner:{
        width: '50%',
        marginTop: 15,
        marginBottom: 10,
        backgroundColor: 'transparent',
        alignItems: 'center',
    },
    deleteAsigButton: {
        position: "absolute",
        right: -15,
        top: 75,
        width: 40,
        height: 40,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: myColors.navyblue,
        borderRadius: 8,
        elevation: 5,
    },
    deleteTutButton: {
        position: "absolute",
        right: -15,
        top: 110,
        width: 40,
        height: 40,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: myColors.navyblue,
        borderRadius: 8,
        elevation: 5,
    },
    validateButton: {
        position: "absolute",
        right: -15,
        top: 20,
        width: 40,
        height: 40,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: myColors.mustard,
        borderRadius: 8,
        elevation: 5,
    },
    validateAstButton: {
        position: "absolute",
        right: -32,
        top: -140,
        width: 40,
        height: 40,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: myColors.mustard,
        borderRadius: 8,
        elevation: 5,
    },
  });